'use client';
import { useEffect, useState, useRef } from 'react';
import { Plus, ArrowUpRight, BriefcaseBusiness, CalendarDays, Check, NotebookPen, ChevronRight, LoaderCircle } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Application, blank, stages } from '@/lib/applications';
import { readRecords, saveRecord, makeBackup, parseBackup, mergeBackup, STORAGE_KEY } from '@/lib/local-storage';

export default function Page(){
 const [rows,setRows]=useState<Application[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[draft,setDraft]=useState<Application>(blank),[saving,setSaving]=useState(false),[formError,setFormError]=useState(''),[notice,setNotice]=useState('');
 const backupInput=useRef<HTMLInputElement>(null);
 function load(){setLoading(true);setError('');try{setRows(readRecords(localStorage));}catch(e){setError(e instanceof Error?e.message:'브라우저 저장소에 접근하지 못했어요.');}finally{setLoading(false);}}
 useEffect(()=>{load(); const refresh=(e:StorageEvent)=>{if(e.key===STORAGE_KEY||e.key===null)load();}; window.addEventListener('storage',refresh); return ()=>window.removeEventListener('storage',refresh);},[]);
 function exportBackup(){try{const text=makeBackup(readRecords(localStorage));const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='applynote-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('백업 파일을 내려받았어요. 안전한 곳에 보관해 주세요.');}catch(e){setNotice(e instanceof Error?e.message:'백업하지 못했어요.');}}
 async function importBackup(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>20_000_000)throw Error('20MB 이하의 백업 파일을 선택해 주세요.');const incoming=parseBackup(await file.text());const result=mergeBackup(localStorage,incoming);setRows(result.records);setNotice(`${result.added}개 기록을 가져왔어요. 중복 ${result.skipped}개는 기존 기록을 유지했어요.`);setError('');}catch(e){setNotice(e instanceof Error?e.message:'파일을 가져오지 못했어요. 기존 기록은 유지됩니다.');}}
 function edit(a?:Application){setDraft(a?{...a}:blank());setFormError('');setOpen(true);}
 function field(key:keyof Application,value:string){setDraft(x=>({...x,[key]:value}));}
 function save(e:React.FormEvent){e.preventDefault();setSaving(true);setFormError('');try{setRows(saveRecord(localStorage,draft));setOpen(false);setNotice('이 브라우저에 지원 기록을 저장했어요.');}catch(e){setFormError(e instanceof Error?e.message:'저장하지 못했어요.');}finally{setSaving(false);}}
 const active=rows.filter(x=>x.stage!=='종료'&&x.stage!=='오퍼').length;
 const interviews=rows.filter(x=>x.stage==='1차 면접'||x.stage==='2차·최종 면접').length;
 const scheduled=rows.filter(x=>x.nextDate&&x.stage!=='종료'&&x.stage!=='오퍼').sort((a,b)=>a.nextDate.localeCompare(b.nextDate));
 return <div className="app-shell">
  <header className="topbar"><a href="./" className="brand"><span className="brand-mark"><NotebookPen size={21}/></span>applynote<span className="brand-dot">.</span></a><span className="private-label">나의 커리어 워크스페이스</span><span className="avatar">ME</span></header>
  <main>
   <div className="heading"><div><div className="eyebrow">MY APPLICATIONS</div><h1>다음 기회를 향한 기록<span>.</span></h1><p>지원한 순간부터 마지막 인터뷰까지, 한곳에서.</p></div><button className="primary" onClick={()=>edit()}><Plus size={19}/>지원 추가</button></div>
   <div className="backup-bar"><span>이 브라우저에 저장됩니다. 브라우저 데이터를 지우기 전에 백업하세요.</span><div><button className="secondary" onClick={exportBackup}>백업 내보내기</button><button className="secondary" onClick={()=>backupInput.current?.click()}>백업 가져오기</button><input ref={backupInput} type="file" accept=".json,application/json" onChange={importBackup} hidden aria-label="백업 파일 선택"/></div></div>
   <section className="overview" aria-label="지원 현황 요약"><div><span>전체 지원</span><strong>{rows.length}<small>개의 기회</small></strong></div><div><span><i className="dot blue"/>진행 중</span><strong>{active}<small>개</small></strong></div><div><span><i className="dot orange"/>면접 진행</span><strong>{interviews}<small>개</small></strong></div><div><span><i className="dot green"/>받은 오퍼</span><strong>{rows.filter(x=>x.stage==='오퍼').length}<small>개</small></strong></div></section>
   <section className="board-section"><div className="section-title"><h2><BriefcaseBusiness size={19}/>지원 보드</h2><span>카드를 눌러 기록을 확인하고 단계를 변경하세요.</span></div>
   {notice&&<div role="status" className="notice"><Check size={16}/>{notice}<button onClick={()=>setNotice('')} aria-label="알림 닫기">×</button></div>}
   {loading?<div className="loading"><LoaderCircle className="spin"/>지원 기록을 불러오는 중…</div>:error?<div className="error" role="alert">{error}<button className="secondary" onClick={load}>다시 불러오기</button></div>:<div className="board">{stages.map((stage,i)=><section className={'lane lane-'+i} key={stage}><div className="lane-title"><h3><i className="dot"/>{stage}</h3><span>{rows.filter(x=>x.stage===stage).length}</span></div><div className="lane-cards">{rows.filter(x=>x.stage===stage).map(a=><button className="job-card" key={a.id} onClick={()=>edit(a)}><div className="card-top"><span className={'company-icon color-'+(a.company.length%4)}>{a.company.slice(0,1).toUpperCase()}</span><ArrowUpRight size={16}/></div><div className="company">{a.company}</div><h4>{a.role}</h4><span className="platform">{a.platform||'직접 지원'}</span>{a.nextDate&&<div className="card-date"><CalendarDays size={14}/>{a.nextDate.replace('T',' · ')}</div>}<div className="card-footer"><span>{a.applied.slice(5).replace('-','.')} 지원</span><span><NotebookPen size={13}/>{a.requirements||a.notes||a.expectations?'기록 있음':'기록 추가'}</span></div></button>)}{!rows.some(x=>x.stage===stage)&&<div className="lane-empty">{i===0?<><BriefcaseBusiness size={24}/><b>새로운 기회의 시작</b><span>지원한 포지션을 추가해 보세요.</span><button onClick={()=>edit()}>+ 첫 지원 기록</button></>:<><span className="empty-dash"/><span>아직 기록이 없어요</span></>}</div>}</div></section>)}</div>}
   </section>
   <section className="bottom-grid"><div className="schedule"><div className="section-title"><h2><CalendarDays size={18}/>면접 일정</h2><span>{scheduled.length}개</span></div>{scheduled.length?scheduled.map(a=><button className="schedule-row" key={a.id} onClick={()=>edit(a)}><span className="date-tile">{a.nextDate.slice(5,7)}월<strong>{a.nextDate.slice(8,10)}</strong></span><span><b>{a.company} · {a.role}</b><small>{a.stage} · {a.nextDate.slice(11)}{new Date(a.nextDate)<new Date()?' · 지난 일정':''}</small></span><ChevronRight size={17}/></button>):<p className="schedule-empty">예정된 면접이 없어요.<br/><span>지원 기록에 다음 면접 날짜를 남겨두세요.</span></p>}</div><aside className="note-panel"><NotebookPen size={24}/><div><div className="eyebrow">A NOTE FOR YOUR NEXT STEP</div><h2>공고가 사라져도,<br/>준비한 기록은 남도록.</h2><p>채용 요구사항과 기대 역할을 붙여넣고,<br/>나의 경험과 연결할 면접 메모를 남겨보세요.</p></div></aside></section>
   <footer>applynote. <span>한 번의 지원, 한 걸음 더.</span></footer>
  </main>
  <Dialog open={open} onOpenChange={v=>{if(!saving)setOpen(v);}}><DialogContent className="editor"><DialogHeader><DialogTitle>{draft.id?'지원 기록':'새로운 지원 추가'}</DialogTitle><DialogDescription>공고 내용과 면접 진행 상황을 함께 기록하세요.</DialogDescription></DialogHeader><form onSubmit={save}>
   <div className="form-grid"><label>회사 <em>*</em><input required maxLength={150} value={draft.company} onChange={e=>field('company',e.target.value)} placeholder="회사 이름"/></label><label>포지션 <em>*</em><input required maxLength={200} value={draft.role} onChange={e=>field('role',e.target.value)} placeholder="예: Product Designer"/></label><label>지원 플랫폼<input value={draft.platform} maxLength={100} onChange={e=>field('platform',e.target.value)} placeholder="LinkedIn, SEEK, 회사 홈페이지…"/></label><label>지원일 <em>*</em><input type="date" required value={draft.applied} onChange={e=>field('applied',e.target.value)}/></label><label className="wide">공고 링크<input type="url" maxLength={3000} value={draft.url} onChange={e=>field('url',e.target.value)} placeholder="https://…"/>{/^https?:\/\//i.test(draft.url)&&<a className="source-link" href={draft.url} target="_blank" rel="noopener noreferrer">원본 공고 열기 <ArrowUpRight size={14}/></a>}</label><label>현재 단계<Select value={draft.stage} onValueChange={v=>v&&field('stage',v)}><SelectTrigger className="stage-select"><SelectValue/></SelectTrigger><SelectContent>{stages.map(s=><SelectItem value={s} key={s}>{s}</SelectItem>)}</SelectContent></Select></label><label>다음 면접 일정<input type="datetime-local" value={draft.nextDate} onChange={e=>field('nextDate',e.target.value)}/></label></div>
   <label className="textarea-label">채용 요구사항 <span>Requirements</span><textarea rows={4} maxLength={30000} value={draft.requirements} onChange={e=>field('requirements',e.target.value)} placeholder="필수 역량, 경력, 기술 스택, 우대 조건 등을 공고에서 붙여넣으세요."/></label>
   <label className="textarea-label">기대 역할 <span>Expectations</span><textarea rows={4} maxLength={30000} value={draft.expectations} onChange={e=>field('expectations',e.target.value)} placeholder="담당 업무, 팀의 목표, 입사 후 기대하는 성과를 기록하세요."/></label>
   <label className="textarea-label">면접 준비 & 메모<textarea rows={4} maxLength={30000} value={draft.notes} onChange={e=>field('notes',e.target.value)} placeholder="예상 질문, 강조할 경험, 면접 피드백, 다음 할 일…"/></label>
   {draft.id&&<div className="history"><h3>진행 이력</h3>{(JSON.parse(draft.history) as {stage:string;date:string}[]).map((h,i)=><span key={i}>{h.stage}<small>{new Date(h.date).toLocaleDateString('ko-KR')}</small></span>)}</div>}
   {formError&&<p className="error" role="alert">{formError}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={saving} onClick={()=>setOpen(false)}>취소</button><button type="submit" className="primary" disabled={saving}>{saving?<LoaderCircle size={17} className="spin"/>:<Check size={17}/>} {saving?'저장 중…':'기록 저장'}</button></div>
  </form></DialogContent></Dialog>
 </div>;
}

